### ISSUE TITLE
RBG (or GBR) Color

### ISSUE THREAD

**Issue by njudd** [shlomenu/raven-gen#1]
Dear maintainer,

I was wondering if you had any tips on how to add color to this package? We would like to generate stimuli for humans.

I found the `COLOR_VALUES` vector on line 33 in `attribute.py`, adding RGB values (e.g., CV = ((255, 224, 196), (255, 224, 196), etc) doesn't seem to work. Any tips would be appreciated!

thanks,
nick

**Comment by shlomenu** [comment]
Hi @njudd, glad you're getting use out of the package! I would like to have an exact solution for you, or implement one officially, but probably can't do that immediately.  To help you right now, I can give the following advice:

The code related to implementing/varying the rules is agnostic to the data associated with the settings of each attribute, so your instinct to modify `COLOR_VALUES` to contain RGB tuples was correct.  The entry point for the rendering is `matrix.py` > `Matrix.save`.  That method primarily delegates to `Matrix.generate_matrix` which relies on `Matrix.render`, which in turn relies on `Entity.render` within `entity.py`; these three methods are all you have to look at to change the way the data underlying any attribute setting is used.  

`Matrix.save` provides a keyword argument for `background_color` which is currently a single integer; this would need to be passed as an RGB tuple to be compatible with the underlying values of `COLOR_VALUES`.  If you examine the methods I mentioned, you will see that `Matrix.generate_matrix` creates the full image by creating an `np.ndarray` of `np.uint8`s initialized to `background_color`, calling `Matrix.render` to create smaller `np.ndarray`s for each panel, overwriting the background within each panel with the returned values, and drawing the necessary grid lines.  Within `Matrix.render`, each panel is created as its own `np.ndarray` of `np.uint8`s initialized to `background_color`; `Entity.render` is called to overwrite these pixels as necessary to create each polygon before the panel is returned to `Matrix.generate_matrix`.  

Within `entity.py` > `Entity.render`, you will see mentions of `self.color.value`.  This will be one of the RGB tuple values you provided by setting `COLOR_VALUES`.  I don't know exactly what error you got, but I would guess that they come from either the error of trying to set a single greyscale channel of an `np.uint8`-valued `np.ndarray`with a tuple-valued `self.color.value`, or they come from comparing an integer `background_color` kwarg with a tuple-valued `self.color.value`.  Either way, hopefully the necessary modifications have become clear: you need to make `Matrix.save`, `Matrix.generate_matrix`, `Matrix.render`, and `Entity.render` RGB-proof.  Across these methods, you want to... 
- Change all `np.ndarray`s initialized to hold greyscale images into `np.ndarray`s appropriate for holding RGB images
- Change the `background_color` keyword argument to an RGB tuple
- Ensure that all assignments to `np.ndarrays` holding images are restructured to assign each color channel appropriately based on an RGB tuple (`background_color` or `self.color.value`).

Please let me know if you have questions about these suggestions!

**Comment by njudd** [comment]
Amazing thanks for your detailed response and tips, I will look into this in a few days!

Making the package more human friendly is kinda a separate goal. So I'll fork it & close the issue, but I might come back here to get some more tips if I can't figure it out. I think there is some use to having a 'human friendly' version next to the machine one. To my knowledge, this is the only openly available matrix generation tool (sandia hasn't been updated for a decade).

**Comment by njudd** [comment]
Just an update on the question to make these more _'human friendly'_.

It seemed to make the most sense (easiest solution) to remap the gray scale values in the save function of `matrix.py`. There is a lot of structure that relies on the current format of ints.

To do this, I commented off Image.fromarray at the end of `generate_matrix`. I than within the save function **1)** use np.repeat to make it 3 values, and then **2)** deterministically subset the gray scale tuples to colors at the end I make it an image. It will be implemented in my fork in the coming weeks. Thanks a million for your help, hopefully the two versions will be able to compliment human to machine research :)
